
### Initialization

Numpy Array Creation Routines

In [1]:
import numpy as np

In [2]:
x = np.empty([3,3])

In [3]:
x

array([[0.00000000e+000, 0.00000000e+000, 6.94582274e-310],
       [6.94582971e-310, 6.94582969e-310, 6.94582963e-310],
       [6.94582965e-310, 6.94582971e-310, 3.95252517e-322]])

An empty array initializes a numpy array with random values

In [4]:
a = np.zeros((3,3,3))

In [5]:
a

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [6]:
np.ones((2,2,4), dtype=int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]])

By using dttype, we can set the type of values that the numpy array contains.

In [7]:
np.full((2,2),"hellottwyyw", dtype='<U7')

array([['hellott', 'hellott'],
       ['hellott', 'hellott']], dtype='<U7')

Note : Only the first 7 characters of the input string were taken into the array elements when we set dtype = '<U7'

In [8]:
np.random.rand(10)

array([0.66726332, 0.43897927, 0.04688608, 0.93075331, 0.31688651,
       0.53722039, 0.33152139, 0.53403819, 0.21897812, 0.02441027])

In [9]:
data = np.random.randint(5,10,(10,10))

### Accessing Numpy Arrays

In [10]:
data[4:8]

array([[7, 5, 6, 5, 7, 6, 7, 5, 5, 8],
       [5, 6, 7, 5, 8, 5, 8, 9, 8, 7],
       [8, 5, 9, 9, 9, 6, 5, 8, 8, 6],
       [7, 8, 7, 6, 8, 8, 6, 7, 5, 5]])

In [11]:
data[4:8,4:6]

array([[7, 6],
       [8, 5],
       [9, 6],
       [8, 8]])

In [12]:
data[4:6,4:6]

array([[7, 6],
       [8, 5]])

## Array Manipulation

A list of functions is listed below for reference


##### CHANGING SHAPE

reshape - Gives new shape to an array without changing its data 
#flat - A 1-D iterator over the array
#flatten - returns the copy of the array collapsed in one dimension
#ravel - returns contiguous flattened array

##### TRANSPOSE OPERATIONS: 

#transpose - permutes the dimnsions of the array
#ndarray.T - same as self.transpose()
#rollaxis - rolls the specified axis backwards
#swapaxes - interchanges the two axes of an array

##### CHANGING DIMENSIONS:

#broadcast - Produces an object that mimics broadcasting
#broadcast_to - broadcasts array to a new shape
#expand_dims - expands the shape of an array
#squeeze - Removes single dimensional entries from the shape of an array

##### JOINING ARRAYS:

#concatenate - Joins a sequence of arrays along an existing axis
#stack - Joins a sequence of arrays along a new axis 
#hstack - Stacks arrays in sequence horizontally
#vstack - stacks arrays in sequence vertically

##### SPLITTING ARRAYS: 

#split - splits an array into multiple sub-arrays
#hsplit - splits an arra into multiple sub arrays horizontally(column-wise)
#vsplit - splits an arra into multiple sub arrays vertically(row-wise)

##### ADDING/REMOVING ELEMENTS: 

#resize - Returns a new array with the specified shape
#append - appends the values to the end of the array
#insert - Inserts the values to the end of an array
#delete - returns a new array with sub arrays along an axis deleted



In [13]:
data1 = np.random.randint(5,15,size=(5,3))

In [14]:
data2 = np.random.randint(5,15,size=(5,3))

In [15]:
np.hstack([data1,data2])

array([[11, 12,  7, 10,  9,  6],
       [11,  9,  9, 11, 13, 14],
       [11,  8,  5, 11,  9, 13],
       [ 7,  8,  8,  5, 11, 12],
       [11, 14, 13,  7,  5,  7]])

np.hstack() takes input as two numpy arrays and stacks them together into a single array 'horizontally'

In [16]:
np.vstack([data1, data2])

array([[11, 12,  7],
       [11,  9,  9],
       [11,  8,  5],
       [ 7,  8,  8],
       [11, 14, 13],
       [10,  9,  6],
       [11, 13, 14],
       [11,  9, 13],
       [ 5, 11, 12],
       [ 7,  5,  7]])

np.vstack() takes input as two numpy arrays and stacks them together into a single array 'vertically'

In [17]:
np.concatenate([data1, data2], axis=1)

array([[11, 12,  7, 10,  9,  6],
       [11,  9,  9, 11, 13, 14],
       [11,  8,  5, 11,  9, 13],
       [ 7,  8,  8,  5, 11, 12],
       [11, 14, 13,  7,  5,  7]])

np.concatenate() appends the second input array at the end pf the first one along the specified axis parameter.

In [18]:
data1 = np.random.randint(5,15,size=(5,3,2))

In [19]:
data2 = np.random.randint(5,15,size=(5,3,2))

In [20]:
np.concatenate([data1, data2], axis=2)

array([[[ 9, 11, 10,  9],
        [ 6,  5, 12, 12],
        [13, 10, 13, 14]],

       [[14,  9, 12, 12],
        [ 8,  5, 11, 12],
        [ 8,  6,  6,  6]],

       [[11, 12,  9,  9],
        [ 5, 12, 14, 12],
        [ 9, 12,  5,  6]],

       [[10, 13, 13, 14],
        [11, 13,  5,  9],
        [ 8,  7, 10,  7]],

       [[13, 14,  6,  6],
        [ 8,  6,  8,  7],
        [11, 12, 12, 10]]])

### Splitting Data

In [21]:
a1,a2 = np.hsplit(data,[5])

In [22]:
a1

array([[7, 7, 7, 6, 7],
       [9, 5, 5, 9, 5],
       [9, 5, 5, 5, 7],
       [9, 5, 7, 7, 9],
       [7, 5, 6, 5, 7],
       [5, 6, 7, 5, 8],
       [8, 5, 9, 9, 9],
       [7, 8, 7, 6, 8],
       [5, 6, 8, 9, 5],
       [8, 9, 8, 9, 7]])

In [23]:
b1,b2,b3 = np.vsplit(data,[5,7])

In [24]:
b1

array([[7, 7, 7, 6, 7, 9, 6, 6, 5, 6],
       [9, 5, 5, 9, 5, 8, 6, 5, 6, 9],
       [9, 5, 5, 5, 7, 7, 7, 8, 6, 6],
       [9, 5, 7, 7, 9, 7, 7, 9, 6, 6],
       [7, 5, 6, 5, 7, 6, 7, 5, 5, 8]])

In [25]:
b2

array([[5, 6, 7, 5, 8, 5, 8, 9, 8, 7],
       [8, 5, 9, 9, 9, 6, 5, 8, 8, 6]])

In [26]:
b3

array([[7, 8, 7, 6, 8, 8, 6, 7, 5, 5],
       [5, 6, 8, 9, 5, 5, 8, 8, 5, 8],
       [8, 9, 8, 9, 7, 6, 5, 7, 9, 5]])

### Shape, Dimension

In [27]:
data.shape

(10, 10)

In [28]:
data.ndim

2

In [29]:
data.size

100

In [30]:
data.reshape(2,50)

array([[7, 7, 7, 6, 7, 9, 6, 6, 5, 6, 9, 5, 5, 9, 5, 8, 6, 5, 6, 9, 9, 5,
        5, 5, 7, 7, 7, 8, 6, 6, 9, 5, 7, 7, 9, 7, 7, 9, 6, 6, 7, 5, 6, 5,
        7, 6, 7, 5, 5, 8],
       [5, 6, 7, 5, 8, 5, 8, 9, 8, 7, 8, 5, 9, 9, 9, 6, 5, 8, 8, 6, 7, 8,
        7, 6, 8, 8, 6, 7, 5, 5, 5, 6, 8, 9, 5, 5, 8, 8, 5, 8, 8, 9, 8, 9,
        7, 6, 5, 7, 9, 5]])

In [31]:
d = np.array([1,2,3,4,5,6,7,9])

In [32]:
d.ndim

1

In [33]:
d.shape

(8,)

In [34]:
d.size

8

In [35]:
d.reshape(8,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [9]])

In [36]:
data.reshape(-1,20)

array([[7, 7, 7, 6, 7, 9, 6, 6, 5, 6, 9, 5, 5, 9, 5, 8, 6, 5, 6, 9],
       [9, 5, 5, 5, 7, 7, 7, 8, 6, 6, 9, 5, 7, 7, 9, 7, 7, 9, 6, 6],
       [7, 5, 6, 5, 7, 6, 7, 5, 5, 8, 5, 6, 7, 5, 8, 5, 8, 9, 8, 7],
       [8, 5, 9, 9, 9, 6, 5, 8, 8, 6, 7, 8, 7, 6, 8, 8, 6, 7, 5, 5],
       [5, 6, 8, 9, 5, 5, 8, 8, 5, 8, 8, 9, 8, 9, 7, 6, 5, 7, 9, 5]])

### Utility Function

In [37]:
np.sum(data)

679

In [38]:
np.sum(data, axis=1)

array([66, 67, 65, 72, 61, 68, 73, 67, 67, 73])

In [39]:
data

array([[7, 7, 7, 6, 7, 9, 6, 6, 5, 6],
       [9, 5, 5, 9, 5, 8, 6, 5, 6, 9],
       [9, 5, 5, 5, 7, 7, 7, 8, 6, 6],
       [9, 5, 7, 7, 9, 7, 7, 9, 6, 6],
       [7, 5, 6, 5, 7, 6, 7, 5, 5, 8],
       [5, 6, 7, 5, 8, 5, 8, 9, 8, 7],
       [8, 5, 9, 9, 9, 6, 5, 8, 8, 6],
       [7, 8, 7, 6, 8, 8, 6, 7, 5, 5],
       [5, 6, 8, 9, 5, 5, 8, 8, 5, 8],
       [8, 9, 8, 9, 7, 6, 5, 7, 9, 5]])

In [40]:
np.sin(data)

array([[ 0.6569866 ,  0.6569866 ,  0.6569866 , -0.2794155 ,  0.6569866 ,
         0.41211849, -0.2794155 , -0.2794155 , -0.95892427, -0.2794155 ],
       [ 0.41211849, -0.95892427, -0.95892427,  0.41211849, -0.95892427,
         0.98935825, -0.2794155 , -0.95892427, -0.2794155 ,  0.41211849],
       [ 0.41211849, -0.95892427, -0.95892427, -0.95892427,  0.6569866 ,
         0.6569866 ,  0.6569866 ,  0.98935825, -0.2794155 , -0.2794155 ],
       [ 0.41211849, -0.95892427,  0.6569866 ,  0.6569866 ,  0.41211849,
         0.6569866 ,  0.6569866 ,  0.41211849, -0.2794155 , -0.2794155 ],
       [ 0.6569866 , -0.95892427, -0.2794155 , -0.95892427,  0.6569866 ,
        -0.2794155 ,  0.6569866 , -0.95892427, -0.95892427,  0.98935825],
       [-0.95892427, -0.2794155 ,  0.6569866 , -0.95892427,  0.98935825,
        -0.95892427,  0.98935825,  0.41211849,  0.98935825,  0.6569866 ],
       [ 0.98935825, -0.95892427,  0.41211849,  0.41211849,  0.41211849,
        -0.2794155 , -0.95892427,  0.98935825

In [41]:
data.T

array([[7, 9, 9, 9, 7, 5, 8, 7, 5, 8],
       [7, 5, 5, 5, 5, 6, 5, 8, 6, 9],
       [7, 5, 5, 7, 6, 7, 9, 7, 8, 8],
       [6, 9, 5, 7, 5, 5, 9, 6, 9, 9],
       [7, 5, 7, 9, 7, 8, 9, 8, 5, 7],
       [9, 8, 7, 7, 6, 5, 6, 8, 5, 6],
       [6, 6, 7, 7, 7, 8, 5, 6, 8, 5],
       [6, 5, 8, 9, 5, 9, 8, 7, 8, 7],
       [5, 6, 6, 6, 5, 8, 8, 5, 5, 9],
       [6, 9, 6, 6, 8, 7, 6, 5, 8, 5]])

In [42]:
data.mean(axis=1)

array([6.6, 6.7, 6.5, 7.2, 6.1, 6.8, 7.3, 6.7, 6.7, 7.3])

In [43]:
data.std(axis=1)

array([1.0198039 , 1.73493516, 1.28452326, 1.32664992, 1.04403065,
       1.4       , 1.55241747, 1.1       , 1.55241747, 1.48660687])

#### A List of String functions

#add() - Returns element wise string concatenation for two arrays of str or unicode
#multiply() - returns the string with multiple concatenation, element wise
#center() -  returns the copy of the given string with elements centred ina a string of specified length
#capitalize() - returns a copy of the string with only the first character capitalized
#title() - returns the element wise title cased version of the string or unicode
#lower() - returns an array with elements converted to lowercase
#upper() - returns an array with the elements converted to uppercase
#split() - returns a list of words in the string, uing separator delimiter
#splitlines() - returns a list of lines in the element, breaking at the line boundaries
#strip() - returns a copy with the leading and trailing characters removed
#join() - returns a copy of the string with all occurences of substring replaced by new string

### Broadcasting

In [44]:
v = np.array([1,2,3,4,5])

In [45]:
s = 10

In [46]:
v + s

array([11, 12, 13, 14, 15])

In [47]:
t = [10,11]

In [48]:
#v + t

In [49]:
a = np.array([[1],[2],[3],[4],[5]])

In [50]:
a.shape

(5, 1)

In [51]:
a + v

array([[ 2,  3,  4,  5,  6],
       [ 3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8],
       [ 5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10]])

In [52]:
a = np.random.randint(1,5,size=(10,2))

In [53]:
b = np.random.randint(1,5,size=(5,2))

In [54]:
a.reshape(1,10,2)

array([[[3, 4],
        [4, 2],
        [1, 2],
        [1, 1],
        [4, 1],
        [4, 4],
        [2, 2],
        [3, 2],
        [2, 4],
        [1, 3]]])

In [55]:
b.reshape(5,1,2) - a.reshape(1,10,2)

array([[[-2, -2],
        [-3,  0],
        [ 0,  0],
        [ 0,  1],
        [-3,  1],
        [-3, -2],
        [-1,  0],
        [-2,  0],
        [-1, -2],
        [ 0, -1]],

       [[-1, -3],
        [-2, -1],
        [ 1, -1],
        [ 1,  0],
        [-2,  0],
        [-2, -3],
        [ 0, -1],
        [-1, -1],
        [ 0, -3],
        [ 1, -2]],

       [[ 0,  0],
        [-1,  2],
        [ 2,  2],
        [ 2,  3],
        [-1,  3],
        [-1,  0],
        [ 1,  2],
        [ 0,  2],
        [ 1,  0],
        [ 2,  1]],

       [[-1, -2],
        [-2,  0],
        [ 1,  0],
        [ 1,  1],
        [-2,  1],
        [-2, -2],
        [ 0,  0],
        [-1,  0],
        [ 0, -2],
        [ 1, -1]],

       [[-1, -3],
        [-2, -1],
        [ 1, -1],
        [ 1,  0],
        [-2,  0],
        [-2, -3],
        [ 0, -1],
        [-1, -1],
        [ 0, -3],
        [ 1, -2]]])

In [56]:
a = np.random.randint(1,5,size=(10,2))
b = np.random.randint(1,5,size=(5,3))

In [57]:
a.shape

(10, 2)

In [58]:
b.shape

(5, 3)

In [59]:
a.reshape(1,10,1,2) - b.reshape(5,1,3,1)

array([[[[ 2,  1],
         [ 0, -1],
         [-1, -2]],

        [[ 3,  3],
         [ 1,  1],
         [ 0,  0]],

        [[ 0,  3],
         [-2,  1],
         [-3,  0]],

        [[ 2,  0],
         [ 0, -2],
         [-1, -3]],

        [[ 3,  3],
         [ 1,  1],
         [ 0,  0]],

        [[ 2,  0],
         [ 0, -2],
         [-1, -3]],

        [[ 3,  3],
         [ 1,  1],
         [ 0,  0]],

        [[ 2,  1],
         [ 0, -1],
         [-1, -2]],

        [[ 1,  1],
         [-1, -1],
         [-2, -2]],

        [[ 3,  3],
         [ 1,  1],
         [ 0,  0]]],


       [[[ 0, -1],
         [ 2,  1],
         [ 2,  1]],

        [[ 1,  1],
         [ 3,  3],
         [ 3,  3]],

        [[-2,  1],
         [ 0,  3],
         [ 0,  3]],

        [[ 0, -2],
         [ 2,  0],
         [ 2,  0]],

        [[ 1,  1],
         [ 3,  3],
         [ 3,  3]],

        [[ 0, -2],
         [ 2,  0],
         [ 2,  0]],

        [[ 1,  1],
         [ 3,  3],
         [ 3,  3

#### STATISTICAL FUNCTIONS


#### numpy.amin() and numpy.amax() 

These functions return the minimum and the maximum from the elements in the given array along the specified axis

In [60]:
a = np.array([[3,7,5],[8,4,3],[2,4,9]])

In [61]:
print(np.amin(a,1))

[3 3 2]


In [62]:
print(np.amin(a,0))

[2 4 3]


In [63]:
print(np.amax(a,1))

[7 8 9]


In [64]:
print(np.amax(a,0))

[8 7 9]


#### numpy.ptp()

This function returns the range (maximum-minimum) of the values along an axis.


In [65]:
print(np.ptp(a))         #with no argument, it takes the entire array for comparison

7


In [66]:
print(np.ptp(a,axis = 1))

[4 5 7]


In [67]:
print(np.ptp(a,axis = 0))

[6 3 6]


#### numpy.percentile() 

Percentile (or a centile) is a measure used in statistics indicating the value below which a given percentage of observations in a group of observations fall. The function numpy.percentile() takes the following arguments.


#### numpy.percentile(a, q, axis)


#a - input array
#q - the percentile to compute (must be between 0 and 100)
#axis - the axis along which percentile is to be caculated

In [68]:
print(a)

[[3 7 5]
 [8 4 3]
 [2 4 9]]


In [69]:
print(np.percentile(a,50)) 

4.0


In [70]:
print(np.percentile(a,50, axis = 1)) 

[5. 4. 4.]


In [71]:
print(np.percentile(a,50, axis = 0))

[3. 4. 5.]
