### NumPy

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])

In [3]:
a

array([1, 2, 3, 4, 5])

In [6]:
np.random.randint(-10,10,(3,3,3))

array([[[ -1,  -2,   4],
        [ -2,  -5,  -9],
        [ -9,  -8,  -5]],

       [[ -4,  -4,  -5],
        [ -3, -10,  -7],
        [  2,   4,   9]],

       [[ -3,   4,  -6],
        [  4,  -2,   7],
        [-10,  -2,  -3]]])

In [8]:
data = np.random.randint(-10,10,(5,5))

In [11]:
np.sin(data)

array([[-0.14112001, -0.90929743,  0.        ,  0.98935825,  0.84147098],
       [ 0.95892427,  0.98935825, -0.41211849, -0.95892427, -0.41211849],
       [-0.95892427,  0.98935825,  0.98935825, -0.41211849,  0.98935825],
       [ 0.54402111, -0.41211849, -0.7568025 ,  0.95892427, -0.41211849],
       [ 0.54402111, -0.98935825, -0.6569866 ,  0.95892427, -0.84147098]])

* Matrix Inverse 

In [12]:
np.linalg.inv(data)

array([[-0.11090818, -0.04075264, -0.07471935, -0.03227229, -0.05143861],
       [ 0.02854952,  0.06115575,  0.06346857, -0.0008369 , -0.00657154],
       [ 0.05711965, -0.01049633,  0.04034037,  0.05825339, -0.04997094],
       [ 0.08117546,  0.00276631, -0.01809442, -0.00671171, -0.02807129],
       [ 0.07497083, -0.02207692,  0.04753443, -0.04479698,  0.05711141]])

In [13]:
data.max()

8

In [14]:
data

array([[ -3,  -2,   0,   8,   1],
       [ -5,   8,  -9,   5,  -9],
       [  5,   8,   8,  -9,   8],
       [-10,  -9,   4,  -5,  -9],
       [-10,  -8,  -7,  -5,  -1]])

In [15]:
data.max(axis=1)

array([ 8,  8,  8,  4, -1])

In [32]:
data

array([[ -3,  -2,   0,   8,   1],
       [ -5,   8,  -9,   5,  -9],
       [  5,   8,   8,  -9,   8],
       [-10,  -9,   4,  -5,  -9],
       [-10,  -8,  -7,  -5,  -1]])

In [18]:
a,b = np.hsplit(data,[2])

In [19]:
a

array([[ -3,  -2],
       [ -5,   8],
       [  5,   8],
       [-10,  -9],
       [-10,  -8]])

In [20]:
b

array([[ 0,  8,  1],
       [-9,  5, -9],
       [ 8, -9,  8],
       [ 4, -5, -9],
       [-7, -5, -1]])

In [33]:
a,b,c = np.vsplit(data,[4,2])

In [34]:
a

array([[ -3,  -2,   0,   8,   1],
       [ -5,   8,  -9,   5,  -9],
       [  5,   8,   8,  -9,   8],
       [-10,  -9,   4,  -5,  -9]])

In [35]:
b

array([], shape=(0, 5), dtype=int64)

In [27]:
c

array([[-10,  -8,  -7,  -5,  -1]])

In [28]:
np.vstack([a,b,c])

array([[ -3,  -2,   0,   8,   1],
       [ -5,   8,  -9,   5,  -9],
       [  5,   8,   8,  -9,   8],
       [-10,  -9,   4,  -5,  -9],
       [-10,  -8,  -7,  -5,  -1]])

In [36]:
data = np.random.randint(1,100,(20))

In [40]:
data[data < 50]

array([42, 40, 10, 27, 49,  6, 39, 16,  1])

In [41]:
data < 50

array([ True, False, False, False, False,  True, False, False, False,
        True, False,  True, False,  True,  True,  True, False,  True,
       False,  True])

In [42]:
data[(data < 50) & (data > 40)]

array([42, 49])

In [54]:
d = np.array([3,4,5])

In [44]:
d + 5

array([ 8,  9, 10, 11])

In [55]:
m = np.array([[1,2,3,4],[5,6,7,8]])

In [58]:
m.shape

(2, 4)

In [59]:
d.shape

(3,)

In [60]:
d.reshape(3,1,1) + m.reshape(1,2,4)

array([[[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 6,  7,  8,  9],
        [10, 11, 12, 13]]])

In [48]:
MData = np.array([[1,2],[5,2],[4,2]])
NData = np.array([[3,1],[4,1]])

In [51]:
MData.shape

(3, 2)

In [52]:
NData.shape

(2, 2)

In [53]:
MData.reshape(1,3,2) + NData.reshape(2,1,2)

array([[[4, 3],
        [8, 3],
        [7, 3]],

       [[5, 3],
        [9, 3],
        [8, 3]]])

### Data Wrangling with Pandas 

In [61]:
import pandas as pd

In [67]:
s1 = pd.Series(['11','22','33','44','55'], index=['a','b','c','d','e'])

In [68]:
s1.dtype

dtype('O')

In [69]:
s1.values

array(['11', '22', '33', '44', '55'], dtype=object)

In [70]:
s1.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [79]:
s2 = pd.Series([111,222,333,444,555], index=['a','b','c','d','e'],dtype=np.float)

In [80]:
pd.DataFrame({'Col1':s1, 'Col2':s2})

Col1   Col2
a   11  111.0
b   22  222.0
c   33  333.0
d   44  444.0
e   55  555.0

In [82]:
hr_data = pd.read_csv('https://raw.githubusercontent.com/edyoda/data-science-complete-tutorial/master/Data/HR_comma_sep.csv.txt')

In [84]:
hr_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 10 columns):
satisfaction_level       14999 non-null float64
last_evaluation          14999 non-null float64
number_project           14999 non-null int64
average_montly_hours     14999 non-null int64
time_spend_company       14999 non-null int64
Work_accident            14999 non-null int64
left                     14999 non-null int64
promotion_last_5years    14999 non-null int64
sales                    14999 non-null object
salary                   14999 non-null object
dtypes: float64(2), int64(6), object(2)
memory usage: 1.1+ MB


In [85]:
hr_data.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years  sales  \
0                   3              0     1                      0  sales   
1                   6              0     1                      0  sales   
2                   4              0     1                      0  sales   
3                   5              0     1                      0  sales   
4                   3              0     1                      0  sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low

In [86]:
hr_data.sales.unique()

array(['sales', 'accounting', 'hr', 'technical', 'support', 'management',
       'IT', 'product_mng', 'marketing', 'RandD'], dtype=object)

In [87]:
hr_data.rename(columns={'sales':'department'}, inplace=True)

In [88]:
hr_data.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years department  \
0                   3              0     1                      0      sales   
1                   6              0     1                      0      sales   
2                   4              0     1                      0      sales   
3                   5              0     1                      0      sales   
4                   3              0     1                      0      sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low

In [90]:
hr_data.salary.value_counts()

low       7316
medium    6446
high      1237
Name: salary, dtype: int64

In [91]:
hr_data.department.value_counts()

sales          4140
technical      2720
support        2229
IT             1227
product_mng     902
marketing       858
RandD           787
accounting      767
hr              739
management      630
Name: department, dtype: int64

In [92]:
hr_data.describe()

satisfaction_level  last_evaluation  number_project  \
count        14999.000000     14999.000000    14999.000000   
mean             0.612834         0.716102        3.803054   
std              0.248631         0.171169        1.232592   
min              0.090000         0.360000        2.000000   
25%              0.440000         0.560000        3.000000   
50%              0.640000         0.720000        4.000000   
75%              0.820000         0.870000        5.000000   
max              1.000000         1.000000        7.000000   

       average_montly_hours  time_spend_company  Work_accident          left  \
count          14999.000000        14999.000000   14999.000000  14999.000000   
mean             201.050337            3.498233       0.144610      0.238083   
std               49.943099            1.460136       0.351719      0.425924   
min               96.000000            2.000000       0.000000      0.000000   
25%              156.000000            3.000000       0.000000      0.000000   
50%              200.000000            3.000000       0.000000      0.000000   
75%              245.000000            4.000000       0.000000      0.000000   
max              310.000000           10.000000       1.000000      1.000000   

       promotion_last_5years  
count           14999.000000  
mean                0.021268  
std                 0.144281  
min                 0.000000  
25%                 0.000000  
50%                 0.000000  
75%                 0.000000  
max                 1.000000

In [98]:
hr_data.select_dtypes(include =['object']).describe()

department salary
count       14999  14999
unique         10      3
top         sales    low
freq         4140   7316

In [95]:
hr_data.select_dtypes(exclude=['object']).head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years  
0                   3              0     1                      0  
1                   6              0     1                      0  
2                   4              0     1                      0  
3                   5              0     1                      0  
4                   3              0     1                      0

In [99]:
hr_data.select_dtypes(include =['float']).describe()

satisfaction_level  last_evaluation
count        14999.000000     14999.000000
mean             0.612834         0.716102
std              0.248631         0.171169
min              0.090000         0.360000
25%              0.440000         0.560000
50%              0.640000         0.720000
75%              0.820000         0.870000
max              1.000000         1.000000

In [103]:
hr_data[5:10]

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
5                0.41             0.50               2                   153   
6                0.10             0.77               6                   247   
7                0.92             0.85               5                   259   
8                0.89             1.00               5                   224   
9                0.42             0.53               2                   142   

   time_spend_company  Work_accident  left  promotion_last_5years department  \
5                   3              0     1                      0      sales   
6                   4              0     1                      0      sales   
7                   5              0     1                      0      sales   
8                   5              0     1                      0      sales   
9                   3              0     1                      0      sales   

  salary  
5    low  
6    low  
7    low  
8    low  
9    low

In [105]:
hr_data.sample(20)

satisfaction_level  last_evaluation  number_project  \
10876                0.53             0.81               3   
9884                 0.91             0.83               4   
9110                 0.72             0.64               3   
9866                 0.12             0.81               4   
10673                0.63             0.72               6   
11649                0.91             0.77               3   
8653                 0.41             0.50               3   
3567                 0.53             0.85               5   
12720                0.42             0.49               2   
8780                 0.83             0.78               5   
7863                 1.00             0.59               3   
14773                0.40             0.57               2   
12181                0.10             0.84               6   
6443                 0.34             0.56               3   
11525                0.83             0.67               3   
9529                 0.51             0.88               5   
6939                 1.00             0.87               3   
3766                 0.44             0.74               5   
3948                 0.76             0.44               4   
5976                 0.98             0.71               5   

       average_montly_hours  time_spend_company  Work_accident  left  \
10876                   275                   2              0     0   
9884                    235                   3              0     0   
9110                    231                   2              0     0   
9866                    287                   6              0     0   
10673                   163                   4              0     0   
11649                   195                   7              0     0   
8653                    193                   3              0     0   
3567                    161                   2              0     0   
12720                   139                   3              0     1   
8780                    240                   3              0     0   
7863                    253                   3              0     0   
14773                   160                   3              0     1   
12181                   261                   4              0     1   
6443                    139                   2              0     0   
11525                   175                   3              0     0   
9529                    225                   2              1     0   
6939                    274                   3              0     0   
3766                    253                   2              0     0   
3948                    192                   4              1     0   
5976                    217                   3              0     0   

       promotion_last_5years   department  salary  
10876                      0    technical     low  
9884                       0    technical     low  
9110                       0   accounting  medium  
9866                       0        sales  medium  
10673                      0           IT    high  
11649                      0        sales  medium  
8653                       0        sales  medium  
3567                       0    technical  medium  
12720                      0           hr     low  
8780                       0   accounting    high  
7863                       0      support     low  
14773                      0   accounting     low  
12181                      0   accounting  medium  
6443                       0           hr  medium  
11525                      0  product_mng  medium  
9529                       0           IT     low  
6939                       0  product_mng  medium  
3766                       0   accounting  medium  
3948                       0    technical     low  
5976                       0        sales  medium

In [110]:
hr_data[(hr_data.salary != 'high') & (hr_data.satisfaction_level > .9) & (hr_data.left == 0)]

satisfaction_level  last_evaluation  number_project  \
2007                 0.99             0.91               5   
2021                 0.98             0.66               5   
2023                 1.00             0.41               4   
2027                 0.92             0.93               4   
2041                 0.98             0.91               4   
...                   ...              ...             ...   
14155                0.99             0.68               5   
14156                0.94             0.73               3   
14159                0.95             0.66               5   
14173                0.92             0.64               2   
14177                0.92             0.65               3   

       average_montly_hours  time_spend_company  Work_accident  left  \
2007                    136                   4              0     0   
2021                    248                   3              0     0   
2023                    174                   3              0     0   
2027                    208                   3              0     0   
2041                    240                   3              0     0   
...                     ...                 ...            ...   ...   
14155                   264                  10              1     0   
14156                   268                  10              0     0   
14159                   192                   3              0     0   
14173                   104                   7              0     0   
14177                   176                   3              0     0   

       promotion_last_5years   department  salary  
2007                       0        sales     low  
2021                       0    technical  medium  
2023                       0    technical     low  
2027                       0    technical  medium  
2041                       0    technical     low  
...                      ...          ...     ...  
14155                      0      support  medium  
14156                      0    technical  medium  
14159                      0    marketing  medium  
14173                      0  product_mng     low  
14177                      0           IT     low  

[1568 rows x 10 columns]

In [111]:
hr_data.department.unique()

array(['sales', 'accounting', 'hr', 'technical', 'support', 'management',
       'IT', 'product_mng', 'marketing', 'RandD'], dtype=object)

In [113]:
def f(d):
    if (d == 'sales') | (d == 'marketing'):
        return 'salesAndMarketing'
    else:
        return d
    
hr_data['new_dept'] = hr_data.department.map(f)

In [116]:
hr_data.sample(10)

satisfaction_level  last_evaluation  number_project  \
12321                0.82             0.84               5   
2474                 0.50             0.55               4   
10711                0.57             0.91               3   
8203                 0.80             0.75               4   
4881                 0.16             0.96               6   
5807                 0.48             0.51               5   
7280                 0.61             0.82               3   
9192                 0.40             0.42               3   
8972                 0.57             0.97               4   
9043                 0.99             0.54               3   

       average_montly_hours  time_spend_company  Work_accident  left  \
12321                   244                   5              0     1   
2474                    148                   3              1     0   
10711                   193                   2              0     0   
8203                    217                   2              0     0   
4881                    211                   6              1     0   
5807                    286                   3              0     0   
7280                    157                   2              0     0   
9192                    146                   2              1     0   
8972                    224                   4              0     0   
9043                    188                   3              0     0   

       promotion_last_5years  department  salary           new_dept  
12321                      0       sales     low  salesAndMarketing  
2474                       0          hr     low                 hr  
10711                      0       sales     low  salesAndMarketing  
8203                       0   technical     low          technical  
4881                       0       RandD     low              RandD  
5807                       0  management     low         management  
7280                       0  accounting     low         accounting  
9192                       0          hr  medium                 hr  
8972                       0   technical  medium          technical  
9043                       0   technical  medium          technical

In [126]:
def f(d):
    return str(int(d/24)) + ' days & ' + str(d%24) + ' hours'
    
hr_data['new_avg_monthly_hrs'] = hr_data.average_montly_hours.map(f)

In [127]:
hr_data.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years department  \
0                   3              0     1                      0      sales   
1                   6              0     1                      0      sales   
2                   4              0     1                      0      sales   
3                   5              0     1                      0      sales   
4                   3              0     1                      0      sales   

   salary           new_dept new_avg_monthly_hrs new_salary  
0     low  salesAndMarketing   6 days & 13 hours        low  
1  medium  salesAndMarketing  10 days & 22 hours       high  
2  medium  salesAndMarketing   11 days & 8 hours       high  
3     low  salesAndMarketing    9 days & 7 hours       high  
4     low  salesAndMarketing   6 days & 15 hours        low

In [128]:
def f(r):
    if r.number_project >= 4:
        return 'high'
    else:
        return r.salary
hr_data['new_salary'] = hr_data.apply(f, axis=1)

In [129]:
hr_data[hr_data.new_salary != hr_data.salary]

satisfaction_level  last_evaluation  number_project  \
1                    0.80             0.86               5   
2                    0.11             0.88               7   
3                    0.72             0.87               5   
6                    0.10             0.77               6   
7                    0.92             0.85               5   
...                   ...              ...             ...   
14987                0.90             0.70               5   
14990                0.89             0.88               5   
14991                0.09             0.81               6   
14993                0.76             0.83               6   
14997                0.11             0.96               6   

       average_montly_hours  time_spend_company  Work_accident  left  \
1                       262                   6              0     1   
2                       272                   4              0     1   
3                       223                   5              0     1   
6                       247                   4              0     1   
7                       259                   5              0     1   
...                     ...                 ...            ...   ...   
14987                   206                   4              0     1   
14990                   228                   5              1     1   
14991                   257                   4              0     1   
14993                   293                   6              0     1   
14997                   280                   4              0     1   

       promotion_last_5years department  salary           new_dept  \
1                          0      sales  medium  salesAndMarketing   
2                          0      sales  medium  salesAndMarketing   
3                          0      sales     low  salesAndMarketing   
6                          0      sales     low  salesAndMarketing   
7                          0      sales     low  salesAndMarketing   
...                      ...        ...     ...                ...   
14987                      0  technical     low          technical   
14990                      0    support     low            support   
14991                      0    support     low            support   
14993                      0    support     low            support   
14997                      0    support     low            support   

      new_avg_monthly_hrs new_salary  
1      10 days & 22 hours       high  
2       11 days & 8 hours       high  
3        9 days & 7 hours       high  
6       10 days & 7 hours       high  
7      10 days & 19 hours       high  
...                   ...        ...  
14987   8 days & 14 hours       high  
14990   9 days & 12 hours       high  
14991  10 days & 17 hours       high  
14993   12 days & 5 hours       high  
14997  11 days & 16 hours       high  

[7867 rows x 13 columns]

In [136]:
titanic_data = pd.read_csv('https://raw.githubusercontent.com/edyoda/data-science-complete-tutorial/master/Data/titanic-train.csv.txt', index_col='PassengerId')

In [139]:
titanic_data['Name_Len'] = titanic_data.Name.str.len()

In [142]:
titanic_data.Name_Len.max()

82

In [146]:
titanic_data[titanic_data.Name_Len == 82]

Survived  Pclass  \
PassengerId                     
308                 1       1   

                                                          Name     Sex   Age  \
PassengerId                                                                    
308          Penasco y Castellana, Mrs. Victor de Satode (M...  female  17.0   

             SibSp  Parch    Ticket   Fare Cabin Embarked  Name_Len  
PassengerId                                                          
308              1      0  PC 17758  108.9   C65        C        82

In [148]:
titanic_data['Name_Words_Len'] =titanic_data.Name.str.split().map(lambda n:len(n))

In [149]:
titanic_data.Name_Words_Len.max()

14

In [150]:
titanic_data[titanic_data.Name_Words_Len == 14]

Survived  Pclass  \
PassengerId                     
308                 1       1   

                                                          Name     Sex   Age  \
PassengerId                                                                    
308          Penasco y Castellana, Mrs. Victor de Satode (M...  female  17.0   

             SibSp  Parch    Ticket   Fare Cabin Embarked  Name_Len  \
PassengerId                                                           
308              1      0  PC 17758  108.9   C65        C        82   

             Name_Words_Len  
PassengerId                  
308                      14

In [152]:
country_data = pd.read_csv('https://raw.githubusercontent.com/edyoda/data-science-complete-tutorial/master/Data/gapminder-FiveYearData.csv')

In [154]:
country_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
country      1704 non-null object
year         1704 non-null int64
pop          1704 non-null float64
continent    1704 non-null object
lifeExp      1704 non-null float64
gdpPercap    1704 non-null float64
dtypes: float64(3), int64(1), object(2)
memory usage: 80.0+ KB


In [155]:
country_data.year.max()

2007

In [156]:
country_data.year.min()

1952

In [161]:
country_data.groupby('country')['gdpPercap'].describe()

count         mean          std          min          25%  \
country                                                                         
Afghanistan          12.0   802.674598   108.202929   635.341351   736.669343   
Albania              12.0  3255.366633  1192.351513  1601.056136  2451.300665   
Algeria              12.0  4426.025973  1310.337656  2449.008185  3188.737834   
Angola               12.0  3607.100529  1165.900251  2277.140884  2724.676675   
Argentina            12.0  8955.553783  1862.583151  5911.315053  7823.006271   
...                   ...          ...          ...          ...          ...   
Vietnam              12.0  1017.712615   567.482251   605.066492   693.697595   
West Bank and Gaza   12.0  3759.996781  1716.840614  1515.592329  2537.025333   
Yemen Rep.           12.0  1569.274672   609.939160   781.717576   853.237410   
Zambia               12.0  1358.199409   247.494984  1071.353818  1195.010683   
Zimbabwe             12.0   635.858042   133.689213   406.884115   525.145203   

                            50%          75%           max  
country                                                     
Afghanistan          803.483195   852.572136    978.011439  
Albania             3253.238396  3657.893725   5937.029526  
Algeria             4853.855903  5386.369921   6223.367465  
Angola              3264.628814  4401.265373   5522.776375  
Argentina           9068.784401  9602.035579  12779.379640  
...                         ...          ...           ...  
Vietnam              742.793140  1088.241554   2441.576404  
West Bank and Gaza  3408.120385  4663.415027   7110.667619  
Yemen Rep.          1854.630925  2012.538889   2280.769906  
Zambia              1291.584180  1486.716399   1777.077318  
Zimbabwe             678.813152   726.831740    799.362176  

[142 rows x 8 columns]

In [162]:
country_data.pivot(index='country',columns='year', values=['lifeExp'])

lifeExp                                                  \
year                  1952    1957    1962    1967    1972    1977    1982   
country                                                                      
Afghanistan         28.801  30.332  31.997  34.020  36.088  38.438  39.854   
Albania             55.230  59.280  64.820  66.220  67.690  68.930  70.420   
Algeria             43.077  45.685  48.303  51.407  54.518  58.014  61.368   
Angola              30.015  31.999  34.000  35.985  37.928  39.483  39.942   
Argentina           62.485  64.399  65.142  65.634  67.065  68.481  69.942   
...                    ...     ...     ...     ...     ...     ...     ...   
Vietnam             40.412  42.887  45.363  47.838  50.254  55.764  58.816   
West Bank and Gaza  43.160  45.671  48.127  51.631  56.532  60.765  64.406   
Yemen Rep.          32.548  33.970  35.180  36.984  39.848  44.175  49.113   
Zambia              42.038  44.077  46.023  47.768  50.107  51.386  51.821   
Zimbabwe            48.451  50.469  52.358  53.995  55.635  57.674  60.363   

                                                            
year                  1987    1992    1997    2002    2007  
country                                                     
Afghanistan         40.822  41.674  41.763  42.129  43.828  
Albania             72.000  71.581  72.950  75.651  76.423  
Algeria             65.799  67.744  69.152  70.994  72.301  
Angola              39.906  40.647  40.963  41.003  42.731  
Argentina           70.774  71.868  73.275  74.340  75.320  
...                    ...     ...     ...     ...     ...  
Vietnam             62.820  67.662  70.672  73.017  74.249  
West Bank and Gaza  67.046  69.718  71.096  72.370  73.422  
Yemen Rep.          52.922  55.599  58.020  60.308  62.698  
Zambia              50.821  46.100  40.238  39.193  42.384  
Zimbabwe            62.351  60.377  46.809  39.989  43.487  

[142 rows x 12 columns]

In [163]:
country_data.pivot(index='year',columns='country', values=['lifeExp'])

lifeExp                                                      \
country Afghanistan Albania Algeria  Angola Argentina Australia Austria   
year                                                                      
1952         28.801  55.230  43.077  30.015    62.485    69.120  66.800   
1957         30.332  59.280  45.685  31.999    64.399    70.330  67.480   
1962         31.997  64.820  48.303  34.000    65.142    70.930  69.540   
1967         34.020  66.220  51.407  35.985    65.634    71.100  70.140   
1972         36.088  67.690  54.518  37.928    67.065    71.930  70.630   
1977         38.438  68.930  58.014  39.483    68.481    73.490  72.170   
1982         39.854  70.420  61.368  39.942    69.942    74.740  73.180   
1987         40.822  72.000  65.799  39.906    70.774    76.320  74.940   
1992         41.674  71.581  67.744  40.647    71.868    77.560  76.040   
1997         41.763  72.950  69.152  40.963    73.275    78.830  77.510   
2002         42.129  75.651  70.994  41.003    74.340    80.370  78.980   
2007         43.828  76.423  72.301  42.731    75.320    81.235  79.829   

                                    ...                                       \
country Bahrain Bangladesh Belgium  ...  Uganda United Kingdom United States   
year                                ...                                        
1952     50.939     37.484  68.000  ...  39.978         69.180        68.440   
1957     53.832     39.348  69.240  ...  42.571         70.420        69.490   
1962     56.923     41.216  70.250  ...  45.344         70.760        70.210   
1967     59.923     43.453  70.940  ...  48.051         71.360        70.760   
1972     63.300     45.252  71.440  ...  51.016         72.010        71.340   
1977     65.593     46.923  72.800  ...  50.350         72.760        73.380   
1982     69.052     50.009  73.930  ...  49.849         74.040        74.650   
1987     70.750     52.819  75.350  ...  51.509         75.007        75.020   
1992     72.601     56.018  76.460  ...  48.825         76.420        76.090   
1997     73.925     59.412  77.530  ...  44.578         77.218        76.810   
2002     74.795     62.013  78.320  ...  47.813         78.471        77.310   
2007     75.635     64.062  79.441  ...  51.542         79.425        78.242   

                                                                         \
country Uruguay Venezuela Vietnam West Bank and Gaza Yemen Rep.  Zambia   
year                                                                      
1952     66.071    55.088  40.412             43.160     32.548  42.038   
1957     67.044    57.907  42.887             45.671     33.970  44.077   
1962     68.253    60.770  45.363             48.127     35.180  46.023   
1967     68.468    63.479  47.838             51.631     36.984  47.768   
1972     68.673    65.712  50.254             56.532     39.848  50.107   
1977     69.481    67.456  55.764             60.765     44.175  51.386   
1982     70.805    68.557  58.816             64.406     49.113  51.821   
1987     71.918    70.190  62.820             67.046     52.922  50.821   
1992     72.752    71.150  67.662             69.718     55.599  46.100   
1997     74.223    72.146  70.672             71.096     58.020  40.238   
2002     75.307    72.766  73.017             72.370     60.308  39.193   
2007     76.384    73.747  74.249             73.422     62.698  42.384   

                  
country Zimbabwe  
year              
1952      48.451  
1957      50.469  
1962      52.358  
1967      53.995  
1972      55.635  
1977      57.674  
1982      60.363  
1987      62.351  
1992      60.377  
1997      46.809  
2002      39.989  
2007      43.487  

[12 rows x 142 columns]

In [164]:
country_data.pivot(index='continent',columns='year', values=['lifeExp'])

ValueError: Index contains duplicate entries, cannot reshape

In [167]:
country_data.pivot_table(index='continent',columns='year',values='lifeExp', aggfunc=np.mean)

year            1952       1957       1962       1967       1972       1977  \
continent                                                                     
Africa     39.135500  41.266346  43.319442  45.334538  47.450942  49.580423   
Americas   53.279840  55.960280  58.398760  60.410920  62.394920  64.391560   
Asia       46.314394  49.318544  51.563223  54.663640  57.319269  59.610556   
Europe     64.408500  66.703067  68.539233  69.737600  70.775033  71.937767   
Oceania    69.255000  70.295000  71.085000  71.310000  71.910000  72.855000   

year            1982       1987       1992       1997       2002       2007  
continent                                                                    
Africa     51.592865  53.344788  53.629577  53.598269  53.325231  54.806038  
Americas   66.228840  68.090720  69.568360  71.150480  72.422040  73.608120  
Asia       62.617939  64.851182  66.537212  68.020515  69.233879  70.728485  
Europe     72.806400  73.642167  74.440100  75.505167  76.700600  77.648600  
Oceania    74.290000  75.320000  76.945000  78.190000  79.740000  80.719500

In [168]:
country_data.pivot_table(index='continent',columns='year',values='pop', aggfunc=np.sum)

year               1952          1957          1962          1967  \
continent                                                           
Africa     2.376405e+08  2.648377e+08  2.965169e+08  3.352895e+08   
Americas   3.451524e+08  3.869539e+08  4.332703e+08  4.807466e+08   
Asia       1.395357e+09  1.562781e+09  1.696357e+09  1.905663e+09   
Europe     4.181208e+08  4.378904e+08  4.603552e+08  4.811790e+08   
Oceania    1.068601e+07  1.194198e+07  1.328352e+07  1.460041e+07   

year               1972          1977          1982          1987  \
continent                                                           
Africa     3.798795e+08  4.330610e+08  4.993486e+08  5.748341e+08   
Americas   5.293842e+08  5.780677e+08  6.302909e+08  6.827540e+08   
Asia       2.150972e+09  2.384514e+09  2.610136e+09  2.871221e+09   
Europe     5.006351e+08  5.171645e+08  5.312669e+08  5.430942e+08   
Oceania    1.610610e+07  1.723900e+07  1.839485e+07  1.957442e+07   

year               1992          1997          2002          2007  
continent                                                          
Africa     6.590815e+08  7.438330e+08  8.337239e+08  9.295397e+08  
Americas   7.392741e+08  7.969004e+08  8.497728e+08  8.988712e+08  
Asia       3.133292e+09  3.383286e+09  3.601802e+09  3.811954e+09  
Europe     5.581428e+08  5.689441e+08  5.782239e+08  5.860985e+08  
Oceania    2.091965e+07  2.224143e+07  2.345483e+07  2.454995e+07

In [169]:
titanic_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 1 to 891
Data columns (total 13 columns):
Survived          891 non-null int64
Pclass            891 non-null int64
Name              891 non-null object
Sex               891 non-null object
Age               714 non-null float64
SibSp             891 non-null int64
Parch             891 non-null int64
Ticket            891 non-null object
Fare              891 non-null float64
Cabin             204 non-null object
Embarked          889 non-null object
Name_Len          891 non-null int64
Name_Words_Len    891 non-null int64
dtypes: float64(2), int64(6), object(5)
memory usage: 97.5+ KB


In [170]:
titanic_data.Age.mean()

29.69911764705882

In [171]:
titanic_data.fillna({'Age':29.6,'Cabin':'NA'}, inplace=True)

In [172]:
titanic_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 1 to 891
Data columns (total 13 columns):
Survived          891 non-null int64
Pclass            891 non-null int64
Name              891 non-null object
Sex               891 non-null object
Age               891 non-null float64
SibSp             891 non-null int64
Parch             891 non-null int64
Ticket            891 non-null object
Fare              891 non-null float64
Cabin             891 non-null object
Embarked          889 non-null object
Name_Len          891 non-null int64
Name_Words_Len    891 non-null int64
dtypes: float64(2), int64(6), object(5)
memory usage: 97.5+ KB


In [173]:
df = pd.DataFrame({'Name':['Abhi','Mac','Ram'],'Marks':[[87,73,22],[22,11],[44,55,66]]})

In [174]:
df

Name         Marks
0  Abhi  [87, 73, 22]
1   Mac      [22, 11]
2   Ram  [44, 55, 66]

In [178]:
df_new = df.explode('Marks')

In [187]:
df_new.reset_index().drop(columns=['index'])

Name Marks
0  Abhi    87
1  Abhi    73
2  Abhi    22
3   Mac    22
4   Mac    11
5   Ram    44
6   Ram    55
7   Ram    66

In [188]:
pd.__version__

'0.25.0'

In [1]:
import pandas as pd

In [2]:
json_data = pd.read_json('../data-science-complete-tutorial/Data/raw_nyc_phil.json')

In [5]:
json_data.head(2)

programs
0  {'season': '1842-43', 'orchestra': 'New York P...
1  {'season': '1842-43', 'orchestra': 'New York P...

In [7]:
df = pd.io.json.json_normalize(json_data['programs'])

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13954 entries, 0 to 13953
Data columns (total 6 columns):
season       13954 non-null object
orchestra    13954 non-null object
concerts     13954 non-null object
programID    13954 non-null object
works        13954 non-null object
id           13954 non-null object
dtypes: object(6)
memory usage: 654.2+ KB


In [10]:
df.concerts

0        [{'Date': '1842-12-07T05:00:00Z', 'eventType':...
1        [{'Date': '1843-02-18T05:00:00Z', 'eventType':...
2        [{'Date': '1843-04-07T05:00:00Z', 'eventType':...
3        [{'Date': '1843-04-22T05:00:00Z', 'eventType':...
4        [{'Date': '1843-11-18T05:00:00Z', 'eventType':...
                               ...                        
13949    [{'Date': '2017-06-24T04:00:00Z', 'eventType':...
13950    [{'Date': '2017-07-02T04:00:00Z', 'eventType':...
13951    [{'Date': '2017-07-03T04:00:00Z', 'eventType':...
13952    [{'Date': '2017-07-04T04:00:00Z', 'eventType':...
13953    [{'Date': '2017-07-07T04:00:00Z', 'eventType':...
Name: concerts, Length: 13954, dtype: object

In [12]:
df = df.explode('concerts')

In [15]:
df.head(1)

season              orchestra  \
0  1842-43  New York Philharmonic   

                                            concerts programID  \
0  {'Date': '1842-12-07T05:00:00Z', 'eventType': ...      3853   

                                               works  \
0  [{'workTitle': 'SYMPHONY NO. 5 IN C MINOR, OP....   

                                     id  
0  38e072a7-8fc9-4f9a-8eac-3957905c0002

In [13]:
pd.io.json.json_normalize(df.concerts)

Date                      eventType  \
0      1842-12-07T05:00:00Z            Subscription Season   
1      1843-02-18T05:00:00Z            Subscription Season   
2      1843-04-07T05:00:00Z                        Special   
3      1843-04-22T05:00:00Z            Subscription Season   
4      1843-11-18T05:00:00Z            Subscription Season   
...                     ...                            ...   
21602  2017-06-24T04:00:00Z                        Chamber   
21603  2017-07-02T04:00:00Z                           Tour   
21604  2017-07-03T04:00:00Z                           Tour   
21605  2017-07-04T04:00:00Z  Tour - Young People's Concert   
21606  2017-07-07T04:00:00Z                           Tour   

                                      Venue          Location    Time  
0                              Apollo Rooms     Manhattan, NY  8:00PM  
1                              Apollo Rooms     Manhattan, NY  8:00PM  
2                              Apollo Rooms     Manhattan, NY  8:00PM  
3                              Apollo Rooms     Manhattan, NY  8:00PM  
4                              Apollo Rooms     Manhattan, NY    None  
...                                     ...               ...     ...  
21602                            Guild Hall  East Hampton, NY    None  
21603                Shanghai Symphony Hall   Shanghai, CHINA  7:30PM  
21604                Shanghai Symphony Hall   Shanghai, CHINA  7:30PM  
21605  Shanghai Symphony Hall--Chamber Hall   Shanghai, CHINA  7:30PM  
21606                Shanghai Symphony Hall   Shanghai, CHINA  7:30PM  

[21607 rows x 5 columns]

In [18]:
df = df.explode('works')

In [27]:
pd.io.json.json_normalize(df.concerts)

Date                      eventType  \
0       1842-12-07T05:00:00Z            Subscription Season   
1       1842-12-07T05:00:00Z            Subscription Season   
2       1842-12-07T05:00:00Z            Subscription Season   
3       1842-12-07T05:00:00Z            Subscription Season   
4       1842-12-07T05:00:00Z            Subscription Season   
...                      ...                            ...   
245036  2017-07-04T04:00:00Z  Tour - Young People's Concert   
245037  2017-07-04T04:00:00Z  Tour - Young People's Concert   
245038  2017-07-07T04:00:00Z                           Tour   
245039  2017-07-07T04:00:00Z                           Tour   
245040  2017-07-07T04:00:00Z                           Tour   

                                       Venue         Location    Time  
0                               Apollo Rooms    Manhattan, NY  8:00PM  
1                               Apollo Rooms    Manhattan, NY  8:00PM  
2                               Apollo Rooms    Manhattan, NY  8:00PM  
3                               Apollo Rooms    Manhattan, NY  8:00PM  
4                               Apollo Rooms    Manhattan, NY  8:00PM  
...                                      ...              ...     ...  
245036  Shanghai Symphony Hall--Chamber Hall  Shanghai, CHINA  7:30PM  
245037  Shanghai Symphony Hall--Chamber Hall  Shanghai, CHINA  7:30PM  
245038                Shanghai Symphony Hall  Shanghai, CHINA  7:30PM  
245039                Shanghai Symphony Hall  Shanghai, CHINA  7:30PM  
245040                Shanghai Symphony Hall  Shanghai, CHINA  7:30PM  

[245041 rows x 5 columns]

In [29]:
works_data = pd.io.json.json_normalize(data=json_data['programs'], record_path='works', 
                            meta=['id', 'orchestra','programID', 'season'])

In [30]:
works_data

workTitle        conductorName  \
0                       SYMPHONY NO. 5 IN C MINOR, OP.67  Hill, Ureli Corelli   
1                                                 OBERON       Timm, Henry C.   
2                        QUINTET, PIANO, D MINOR, OP. 74                  NaN   
3                                                    NaN                  NaN   
4                                                 OBERON    Etienne, Denis G.   
...                                                  ...                  ...   
82788                           MEMORIES OF MARNYI STONE       Gersen, Joshua   
82789  SYMPHONY NO. 9, E MINOR, OP.95 (FROM THE NEW W...       Gersen, Joshua   
82790                                         QUIET CITY        Gilbert, Alan   
82791                       JUNGLE, THE (SYMPHONY NO. 4)        Gilbert, Alan   
82792                                        C JAM BLUES                  NaN   

           ID                                           soloists  \
0      52446*                                                 []   
1      8834*4  [{'soloistName': 'Otto, Antoinette', 'soloistR...   
2       3642*  [{'soloistName': 'Scharfenberg, William', 'sol...   
3          0*                                                 []   
4      8834*3                                                 []   
...       ...                                                ...   
82788  12636*                                                 []   
82789  2877*4                                                 []   
82790  52332*  [{'soloistName': 'Martin, Christopher', 'soloi...   
82791  12071*  [{'soloistName': 'Jazz at Lincoln Center Orche...   
82792   8152*  [{'soloistName': 'Jazz at Lincoln Center Orche...   

                  composerName  \
0      Beethoven,  Ludwig  van   
1      Weber,  Carl  Maria Von   
2              Hummel,  Johann   
3                          NaN   
4      Weber,  Carl  Maria Von   
...                        ...   
82788             Feng,  Shuya   
82789         Dvorak,  Antonín   
82790          Copland,  Aaron   
82791        Marsalis,  Wynton   
82792         Ellington,  Duke   

                                                movement      interval  \
0                                                    NaN           NaN   
1      "Ozean, du Ungeheuer" (Ocean, thou mighty mons...           NaN   
2                                                    NaN           NaN   
3                                                    NaN  Intermission   
4                                               Overture           NaN   
...                                                  ...           ...   
82788                                                NaN           NaN   
82789                                  Allegro con fuoco           NaN   
82790                                                NaN           NaN   
82791                                                NaN           NaN   
82792                                                NaN           NaN   

      movement.em movement._ workTitle.em workTitle._  \
0             NaN        NaN          NaN         NaN   
1             NaN        NaN          NaN         NaN   
2             NaN        NaN          NaN         NaN   
3             NaN        NaN          NaN         NaN   
4             NaN        NaN          NaN         NaN   
...           ...        ...          ...         ...   
82788         NaN        NaN          NaN         NaN   
82789         NaN        NaN          NaN         NaN   
82790         NaN        NaN          NaN         NaN   
82791         NaN        NaN          NaN         NaN   
82792         NaN        NaN          NaN         NaN   

                                         id              orchestra programID  \
0      38e072a7-8fc9-4f9a-8eac-3957905c0002  New York Philharmonic      3853   
1      38e072a7-8fc9-4f9a-8eac-3957905c0002  New York Philharmonic      3853   
2      38e072a7-8fc9-4f9a-8eac-395