In [1]:
l = [1,'Hello',2.2,5]

In [2]:
l

[1, 'Hello', 2.2, 5]

In [3]:
l1 = [1.1,l]

In [4]:
l1

[1.1, [1, 'Hello', 2.2, 5]]

In [2]:
import numpy as np

### Create NumPy Array from Python List

In [3]:
a = np.array([1,2,3,4])

In [4]:
a.shape

(4,)

In [13]:
data = np.random.randint(10, 100, (5,5))

In [6]:
data  

array([[50, 50, 97, 20, 33],
       [68, 40, 74, 33, 79],
       [33, 96, 16, 85, 75],
       [42, 49, 23, 35, 32],
       [96, 66, 82, 71, 89]])

In [7]:
data.shape

(5, 5)

In [8]:
data.ndim

2

In [9]:
data.size

25

In [10]:
data.max()

97

In [11]:
np.sin(data)

array([[-0.26237485, -0.26237485,  0.37960774,  0.91294525,  0.99991186],
       [-0.89792768,  0.74511316, -0.98514626,  0.99991186, -0.44411267],
       [ 0.99991186,  0.98358775, -0.28790332, -0.17607562, -0.38778164],
       [-0.91652155, -0.95375265, -0.8462204 , -0.42818267,  0.55142668],
       [ 0.98358775, -0.02655115,  0.31322878,  0.95105465,  0.86006941]])

In [12]:
np.linalg.inv(data)

array([[-0.01042192, -0.00055567, -0.01778947,  0.03854819,  0.00548865],
       [ 0.00590693,  0.01348381,  0.00298488,  0.03875234, -0.03060777],
       [ 0.01528493, -0.00900967,  0.00351046, -0.02767716,  0.00932299],
       [ 0.00293678, -0.04170059,  0.00849387, -0.04720859,  0.04574234],
       [-0.00956437,  0.03216795,  0.00696477, -0.00715668, -0.01706728]])

In [14]:
data = np.array([1,2,3])

In [15]:
data

array([1, 2, 3])

In [16]:
data = np.random.randint(10, 100, (5,5))

In [17]:
data

array([[63, 55, 44, 34, 67],
       [30, 11, 68, 32, 17],
       [82, 16, 96, 96, 89],
       [80, 58, 22, 40, 82],
       [40, 71, 62, 91, 91]])

### Maximum value across each row

In [18]:
data.max()

96

In [19]:
data.max(axis=1)

array([67, 68, 96, 82, 91])

In [20]:
data.max(axis=0)

array([82, 71, 96, 96, 91])

### Understanding Vectors & Scalers
* Scaler value has to be broadcasted

In [21]:
a = np.array([1,2,3,4,5])

In [22]:
a + 5

array([ 6,  7,  8,  9, 10])

### Genrating Data from subset of data

In [24]:
np.choose([1,2,1,1,1,1,1,1],choices=['hello','hi','hola','hey'])

array(['hi', 'hola', 'hi', 'hi', 'hi', 'hi', 'hi', 'hi'], dtype='<U5')

In [26]:
from skimage.io import imread

In [28]:
img = imread('/home/awantik/Pictures/child-fedex.jpg')

In [29]:
img.shape

(194, 260, 3)